import { LogoMark } from "@/components/brand/logo";
import { formatPhone } from "@/lib/phone";
import { PrintButton } from "./print-button";

export type ClinicProfile = Partial<Record<"name" | "tagline" | "address" | "city" | "phone" | "whatsapp" | "email" | "website", string>>;

/** A4 page with the clinic letterhead. Screen shows a print button; print hides it. */
export function PrintShell({ clinic, title, children, footer }: {
  clinic: ClinicProfile; title: string; children: React.ReactNode; footer?: React.ReactNode;
}) {
  const contact = [clinic.address, clinic.city].filter(Boolean).join(", ");
  const phones = [clinic.phone && `Tel ${formatPhone(clinic.phone)}`, clinic.whatsapp && `WhatsApp ${formatPhone(clinic.whatsapp)}`]
    .filter(Boolean).join(" · ");
  return (
    <div className="min-h-svh bg-muted py-8 print:bg-white print:py-0">
      <div className="no-print mx-auto mb-4 flex max-w-[210mm] justify-end px-4"><PrintButton /></div>
      <article className="mx-auto flex min-h-[297mm] max-w-[210mm] flex-col bg-white p-[14mm] text-[13px] leading-relaxed text-ink shadow-float print:min-h-0 print:p-[10mm] print:shadow-none">
        <header className="flex items-center gap-4 border-b-2 border-brand pb-4">
          <LogoMark tone="ink" className="w-14" priority />
          <div className="flex-1">
            <p className="font-heading text-xl leading-tight font-bold tracking-tight">{(clinic.name || "Bin Dawood Animal Hospital").toUpperCase()}</p>
            <p className="text-xs font-medium tracking-[0.12em] text-brand">BY DR. MUSAB BIN DAWOOD</p>
          </div>
          <div className="text-right text-[11px] text-muted-foreground">
            {contact && <p>{contact}</p>}
            {phones && <p>{phones}</p>}
            {clinic.email && <p>{clinic.email}</p>}
          </div>
        </header>
        <h1 className="mt-5 text-center text-sm font-bold tracking-[0.2em] text-brand uppercase">{title}</h1>
        <div className="mt-4 flex-1">{children}</div>
        <footer className="mt-8 border-t pt-3 text-center text-[10px] text-muted-foreground">
          {footer ?? "Generated by the Bin Dawood Animal Hospital system."}
        </footer>
      </article>
    </div>
  );
}

export function InfoGrid({ rows }: { rows: [string, React.ReactNode][] }) {
  return (
    <dl className="grid grid-cols-2 gap-x-6 gap-y-1.5 rounded-lg bg-surface p-3 print:bg-transparent print:p-0">
      {rows.filter(([, v]) => v).map(([k, v]) => (
        <div key={k} className="flex gap-2">
          <dt className="w-24 shrink-0 text-muted-foreground">{k}</dt>
          <dd className="font-medium">{v}</dd>
        </div>
      ))}
    </dl>
  );
}
